_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.10
        t:
            "1":
                - 1
                - 37
                - 38
                - 55
                - 82
            "2":
                - 1
                - 37
                - 38
                - 55
                - 82
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.7.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
